### ISSUE TITLE
for hacktoberfest. Create new features for discord bot made in python

### ISSUE THREAD

**Issue by Attupatil** [Attupatil/Discord-Bot#1]

**Comment by aewens** [comment]
A recent update has made hacktoberfest opt-in via adding a topic to the repository (due to the spam issue on unsuspecting repos). For PRs to count for the issues flagged as being for hacktoberfest, the topic needs to be added to the repository as well. See here for more details:

https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by Attupatil** [comment]
Yes I had made the changes yesterday itself and by the way all the PR before 3oct will follow the same rule as old soo don't worry about your previous pr😊

**Comment by PranavMurali** [comment]
@Attupatil what kind of features are you looking for?

**Comment by Attupatil** [comment]
Hello @PranavMurali any cool features

**Comment by PranavMurali** [comment]
I added a covid19 data tracker to the bot @Attupatil
